name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install frontend
        run: |
          cd frontend
          npm install
      - name: lint frontend
        run: |
          cd frontend
          npm run lint
      - name: npm install backend
        run: |
          cd backend
          npm install
      - name: build
        run: |
          cd backend
          npm run build:ui
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: minhsenger
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
      - name: discord success notification
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: ${{ github.event_name == 'push' && success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: "[{\"author\":{\"name\":\"${{github.event.head_commit.author.name}}\",\"url\":\"${{github.event.sender.html_url}}\",\"icon_url\":\"${{github.event.sender.avatar_url}}\"},\"description\":\"[${{github.event.head_commit.id}}](${{github.event.head_commit.url}}) ${{github.event.head_commit.message}}\",\"allowed_mentions\":{\"parse\":[\"everyone\"]},\"footer\":{\"text\":\"Woah! *So cool!* :100: :100: :100:\",\"icon_url\":\"https://img.icons8.com/emoji/96/000000/check-mark-emoji.png\"}}]"
      - name: discord failure notification
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: ${{ github.event_name == 'push' && failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: "[{\"author\":{\"name\":\"${{github.event.head_commit.author.name}}\",\"url\":\"${{github.event.sender.html_url}}\",\"icon_url\":\"${{github.event.sender.avatar_url}}\"},\"description\":\"[${{github.event.head_commit.id}}](${{github.event.head_commit.url}}) ${{github.event.head_commit.message}}\",\"allowed_mentions\":{\"parse\":[\"everyone\"]},\"footer\":{\"text\":\"Oops! *Something wrong!* :bug: :tools:\",\"icon_url\":\"https://img.icons8.com/fluent/96/000000/error.png\"}}]"

          
